"use strict";
import { BaseContract, Contract, ContractFactory } from "@corepass/corebc-contracts";
import { BigNumber, FixedNumber } from "@corepass/corebc-bignumber";
import { Signer, VoidSigner } from "@corepass/corebc-abstract-signer";
import { Wallet } from "@corepass/corebc-wallet";
import * as constants from "@corepass/corebc-constants";
import * as providers from "@corepass/corebc-providers";
import { getDefaultProvider } from "@corepass/corebc-providers";
import { Wordlist, wordlists } from "@corepass/corebc-wordlists";
import * as utils from "./utils";
import { ErrorCode as errors, Logger } from "@corepass/corebc-logger";
////////////////////////
// Compile-Time Constants
// This is generated by "npm run dist"
import { version } from "./_version";
const logger = new Logger(version);
////////////////////////
// Exports
export { Signer, Wallet, VoidSigner, getDefaultProvider, providers, BaseContract, Contract, ContractFactory, BigNumber, FixedNumber, constants, errors, logger, utils, wordlists, 
////////////////////////
// Compile-Time Constants
version, Wordlist };
//# sourceMappingURL=corebc.js.map