"use strict";

import { BaseContract, Contract, ContractFactory } from "@corepass/corebc-contracts";

import { BigNumber, FixedNumber } from "@corepass/corebc-bignumber";

import { Signer, VoidSigner } from "@corepass/corebc-abstract-signer";
import { Wallet } from "@corepass/corebc-wallet";

import * as constants from "@corepass/corebc-constants";

import * as providers from "@corepass/corebc-providers";
import { getDefaultProvider } from "@corepass/corebc-providers";

import { Wordlist, wordlists} from "@corepass/corebc-wordlists";

import * as utils from "./utils";

import { ErrorCode as errors, Logger } from "@corepass/corebc-logger";

////////////////////////
// Types

import { BigNumberish } from "@corepass/corebc-bignumber";
import { Bytes, BytesLike } from "@corepass/corebc-bytes";
import { Transaction, UnsignedTransaction } from "@corepass/corebc-transactions";


////////////////////////
// Compile-Time Constants

// This is generated by "npm run dist"
import { version } from "./_version";

const logger = new Logger(version);

////////////////////////
// Types

import {
    ContractFunction,
    ContractReceipt,
    ContractTransaction,

    Event,
    EventFilter,

    Overrides,
    PayableOverrides,
    CallOverrides,

    PopulatedTransaction,

    ContractInterface
} from "@corepass/corebc-contracts";


////////////////////////
// Exports

export {
    Signer,

    Wallet,
    VoidSigner,

    getDefaultProvider,
    providers,

    BaseContract,
    Contract,
    ContractFactory,

    BigNumber,
    FixedNumber,

    constants,
    errors,

    logger,

    utils,

    wordlists,


    ////////////////////////
    // Compile-Time Constants

    version,


    ////////////////////////
    // Types

    ContractFunction,
    ContractReceipt,
    ContractTransaction,
    Event,
    EventFilter,

    Overrides,
    PayableOverrides,
    CallOverrides,

    PopulatedTransaction,

    ContractInterface,

    BigNumberish,

    Bytes,
    BytesLike,

    Transaction,
    UnsignedTransaction,

    Wordlist
};

