'use strict';

var Tes__factory = require('./Tes__factory.js');

/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

exports.Tes__factory = Tes__factory.Tes__factory;
//# sourceMappingURL=index.js.map
