"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tes__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Tes__factory_js_1 = require("./Tes__factory.js");
Object.defineProperty(exports, "Tes__factory", { enumerable: true, get: function () { return Tes__factory_js_1.Tes__factory; } });
//# sourceMappingURL=index.js.map