/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Tes } from "./Tes.js";
export * as factories from "./factories/index.js";
export { Tes__factory } from "./factories/Tes__factory.js";
